package fr.formation.afpa.domain;
// Generated 10 mai 2021 12:01:41 by Hibernate Tools 5.2.12.Final

import java.util.Date;

/**
 * AccTransaction generated by hbm2java
 */
public class AccTransaction implements java.io.Serializable {

	private Long txnId;
	private Account account;
	private Branch branch;
	private Employee employee;
	private float amount;
	private Date fundsAvailDate;
	private Date txnDate;
	private String txnTypeCd;

	public AccTransaction() {
	}

	public AccTransaction(float amount, Date fundsAvailDate, Date txnDate) {
		this.amount = amount;
		this.fundsAvailDate = fundsAvailDate;
		this.txnDate = txnDate;
	}

	public AccTransaction(Account account, Branch branch, Employee employee, float amount, Date fundsAvailDate,
			Date txnDate, String txnTypeCd) {
		this.account = account;
		this.branch = branch;
		this.employee = employee;
		this.amount = amount;
		this.fundsAvailDate = fundsAvailDate;
		this.txnDate = txnDate;
		this.txnTypeCd = txnTypeCd;
	}

	public Long getTxnId() {
		return this.txnId;
	}

	public void setTxnId(Long txnId) {
		this.txnId = txnId;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public Branch getBranch() {
		return this.branch;
	}

	public void setBranch(Branch branch) {
		this.branch = branch;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public float getAmount() {
		return this.amount;
	}

	public void setAmount(float amount) {
		this.amount = amount;
	}

	public Date getFundsAvailDate() {
		return this.fundsAvailDate;
	}

	public void setFundsAvailDate(Date fundsAvailDate) {
		this.fundsAvailDate = fundsAvailDate;
	}

	public Date getTxnDate() {
		return this.txnDate;
	}

	public void setTxnDate(Date txnDate) {
		this.txnDate = txnDate;
	}

	public String getTxnTypeCd() {
		return this.txnTypeCd;
	}

	public void setTxnTypeCd(String txnTypeCd) {
		this.txnTypeCd = txnTypeCd;
	}

}
