package fr.formation.afpa.domain;
// Generated 10 mai 2021 12:01:41 by Hibernate Tools 5.2.12.Final

/**
 * Compte generated by hbm2java
 */
public class Compte implements java.io.Serializable {

	private Integer id;
	private Customer customer;
	private String login;
	private String password;

	public Compte() {
	}

	public Compte(Customer customer) {
		this.customer = customer;
	}

	public Compte(Customer customer, String login, String password) {
		this.customer = customer;
		this.login = login;
		this.password = password;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
