package fr.formation.afpa.domain;
// Generated 10 mai 2021 12:01:41 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Formation generated by hbm2java
 */
public class Formation implements java.io.Serializable {

	private int idFormation;
	private String formationName;
	private Set employees = new HashSet(0);

	public Formation() {
	}

	public Formation(int idFormation) {
		this.idFormation = idFormation;
	}

	public Formation(int idFormation, String formationName, Set employees) {
		this.idFormation = idFormation;
		this.formationName = formationName;
		this.employees = employees;
	}

	public int getIdFormation() {
		return this.idFormation;
	}

	public void setIdFormation(int idFormation) {
		this.idFormation = idFormation;
	}

	public String getFormationName() {
		return this.formationName;
	}

	public void setFormationName(String formationName) {
		this.formationName = formationName;
	}

	public Set getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set employees) {
		this.employees = employees;
	}

}
