package fr.formation.afpa.domain;
// Generated 10 mai 2021 12:01:41 by Hibernate Tools 5.2.12.Final

import java.util.Date;

/**
 * Officer generated by hbm2java
 */
public class Officer implements java.io.Serializable {

	private Integer officerId;
	private Customer customer;
	private Date endDate;
	private String firstName;
	private String lastName;
	private Date startDate;
	private String title;

	public Officer() {
	}

	public Officer(String firstName, String lastName, Date startDate) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.startDate = startDate;
	}

	public Officer(Customer customer, Date endDate, String firstName, String lastName, Date startDate, String title) {
		this.customer = customer;
		this.endDate = endDate;
		this.firstName = firstName;
		this.lastName = lastName;
		this.startDate = startDate;
		this.title = title;
	}

	public Integer getOfficerId() {
		return this.officerId;
	}

	public void setOfficerId(Integer officerId) {
		this.officerId = officerId;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

}
